### ISSUE TITLE
extracting each branch in a rooted tree and branches cover some taxa

### ISSUE THREAD

**Issue by jianshu93** [lucblassel/phylotree-rs#11]
Hi @lucblassel,

This is just to copy the email to you here so that more people can understand the problem/feature that I want to use:

For a pair of sample with some taxa, all those taxa are in a tree, the we compare those samples based on the tree. In practise, there are several thousand such taxa and how to extract the branch length and p_A, p_B is expensive, as expensive as compute p_A*B*p_B. I would love to  use phylotree as the tree handling library. In the end, we need a distance function, where the input is a S_A & S_B table and a rooted tree, the output is a distance.

![IMG_3422](https://github.com/user-attachments/assets/4f235af6-6443-4cbf-becd-4fb32085241d)

Thanks,
Jianshu

**Comment by lucblassel** [comment]
I have implemented this MWE [here](https://github.com/lucblassel/unifrac_test). 
I'm sure there are plenty of improvements to make, but do let me know if that is something that looks like what you would need.
